# Generated by Django 5.1.4 on 2024-12-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteApellido',
            field=models.CharField(db_column='cliente_apellido', max_length=100, verbose_name='Apellido del cliente'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteDni',
            field=models.CharField(db_column='cliente_dni', max_length=10, unique=True, verbose_name='DNI del cliente'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteId',
            field=models.AutoField(db_column='cliente_id', primary_key=True, serialize=False, unique=True, verbose_name='ID del cliente'),
        ),
        migrations.CreateModel(
            name='AsistenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistenciaFecha', models.DateField(auto_now_add=True, db_column='cliente_asistencia', verbose_name='Fecha de asistencia del cliente')),
                ('asistenciaHoraEntrada', models.TimeField(auto_now_add=True, db_column='cliente_hora_entrada', verbose_name='Hora de entrada del cliente')),
                ('clienteId', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gymtemploadmin.clientemodel', verbose_name='ID del cliente')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'db_table': 't_asistencia',
            },
        ),
    ]
