# Generated by Django 5.1.4 on 2024-12-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0002_alter_clientemodel_clienteapellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciamodel',
            options={'verbose_name': 'asistencia', 'verbose_name_plural': 'asistencias clientes'},
        ),
        migrations.AlterField(
            model_name='asistenciamodel',
            name='asistenciaFecha',
            field=models.DateField(auto_now_add=True, db_column='cliente_asistencia', verbose_name='Fecha de asistencia'),
        ),
        migrations.AlterField(
            model_name='asistenciamodel',
            name='asistenciaHoraEntrada',
            field=models.TimeField(auto_now_add=True, db_column='cliente_hora_entrada', verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='asistenciamodel',
            name='clienteId',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gymtemploadmin.clientemodel', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteApellido',
            field=models.CharField(db_column='cliente_apellido', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteCelular',
            field=models.CharField(db_column='cliente_celular', max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteCorreo',
            field=models.EmailField(db_column='cliente_correo', max_length=30, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteDni',
            field=models.CharField(db_column='cliente_dni', max_length=10, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteFechaNacimiento',
            field=models.DateField(db_column='cliente_fecha_nacimiento', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteFechaRegistro',
            field=models.DateTimeField(auto_now_add=True, db_column='cliente_fecha_registro', verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteId',
            field=models.AutoField(db_column='cliente_id', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteNombre',
            field=models.CharField(db_column='cliente_nombre', max_length=100, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='MembresiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membresiaTipo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], db_column='membresia_tipo', max_length=50, verbose_name='Tipo')),
                ('membresiaPrecio', models.DecimalField(db_column='membresia_precio', decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('membresiaDuracion', models.PositiveIntegerField(db_column='membresia_duracion', verbose_name='Duracion(días)')),
                ('clienteId', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gymtemploadmin.clientemodel', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'membresia',
                'verbose_name_plural': 'membresias',
                'db_table': 't_membresia',
            },
        ),
    ]
