# Generated by Django 5.1.4 on 2024-12-25 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0003_alter_asistenciamodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiamodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membresiamodel',
            name='membresiaInicio',
            field=models.DateField(auto_now_add=True, db_column='membresia_registro', default=datetime.date(2023, 1, 1), verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
    ]
