# Generated by Django 5.1.4 on 2024-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0004_membresiamodel_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoModel',
            fields=[
                ('empleadoId', models.AutoField(db_column='empleado_id', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('empleadoDni', models.CharField(db_column='empleado_dni', max_length=10, unique=True, verbose_name='DNI')),
                ('empleadoNombre', models.CharField(db_column='empleado_nombre', max_length=100, verbose_name='Nombre')),
                ('empleadoApellido', models.CharField(db_column='empleado_apellido', max_length=100, verbose_name='Apellido')),
                ('empleadoFechaNacimiento', models.DateField(db_column='empleado_fecha_nacimiento', verbose_name='Fecha de nacimiento')),
                ('empleadoCelular', models.CharField(db_column='empleado_celular', max_length=15, verbose_name='Celular')),
                ('empleadoCorreo', models.EmailField(db_column='empleado_correo', max_length=30, unique=True, verbose_name='Correo')),
                ('empleadoFechaRegistro', models.DateTimeField(auto_now_add=True, db_column='empleado_fecha_registro', verbose_name='Fecha de registro')),
                ('empleadoFechaContratacion', models.DateTimeField(db_column='empleado_fecha_contratacion', verbose_name='Fecha de contratacion')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 't_empleado',
            },
        ),
    ]
