# Generated by Django 5.1.4 on 2024-12-26 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0005_empleadomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistenciaEmpleadoFecha', models.DateField(auto_now_add=True, db_column='empleado_asistencia', verbose_name='Fecha de asistencia')),
                ('asistenciaEmpleadoHoraEntrada', models.TimeField(auto_now_add=True, db_column='empleado_hora_entrada', verbose_name='Hora de entrada')),
                ('empleadoId', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gymtemploadmin.empleadomodel', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'asistencia empleado',
                'verbose_name_plural': 'asistencias empleados',
                'db_table': 't_asistencia_empleado',
            },
        ),
    ]
