# Generated by Django 5.1.4 on 2024-12-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0007_alter_asistenciaempleadomodel_empleadoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaempleadomodel',
            name='empleadoId',
            field=models.ForeignKey(db_column='empleado_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_empleado', to='gymtemploadmin.empleadomodel', verbose_name='ID'),
        ),
    ]
