# Generated by Django 5.1.4 on 2024-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0008_alter_asistenciaempleadomodel_empleadoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='clienteGenero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], db_column='cliente_genero', default='masculino', max_length=50, verbose_name='Genero'),
        ),
    ]
