# Generated by Django 5.1.4 on 2024-12-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0010_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelTable(
            name='productos',
            table='t_productos',
        ),
    ]
