# Generated by Django 5.1.4 on 2024-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0012_productos_productocategoria_ventasmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventamodel',
            options={'verbose_name': 'detalle', 'verbose_name_plural': 'detalles'},
        ),
        migrations.RemoveField(
            model_name='detalleventamodel',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detalleventamodel',
            name='cantidad',
            field=models.IntegerField(db_column='producto_cantidad', default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterModelTable(
            name='detalleventamodel',
            table='t_detalles',
        ),
    ]
