# Generated by Django 5.1.4 on 2024-12-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0013_alter_detalleventamodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventamodel',
            name='subtotal',
            field=models.DecimalField(blank=True, db_column='subtotal', decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
