# Generated by Django 5.1.4 on 2024-12-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0016_alter_ventasmodel_ventaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='clienteDireccion',
            field=models.CharField(db_column='cliente_direccion', default='calle A S/N, San Martin de Porres', max_length=150, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='detalleventamodel',
            name='detalleId',
            field=models.AutoField(db_column='detalle_id', primary_key=True, serialize=False, unique=True, verbose_name='ID Detalle'),
        ),
        migrations.AlterField(
            model_name='detalleventamodel',
            name='ventaId',
            field=models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gymtemploadmin.ventasmodel', verbose_name='ID Venta'),
        ),
    ]
