# Generated by Django 5.1.4 on 2024-12-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0017_clientemodel_clientedireccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteModel',
            fields=[
                ('comprobanteId', models.AutoField(db_column='comprobante_id', primary_key=True, serialize=False, unique=True, verbose_name='ID Comprobante')),
                ('enlace_pdf', models.URLField(blank=True, db_column='comprobante_pdf', max_length=500, null=True, verbose_name='Enlace del PDF')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fecha', verbose_name='Fecha de Generación')),
                ('ventaId', models.OneToOneField(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='gymtemploadmin.ventasmodel', verbose_name='ID Venta')),
            ],
            options={
                'verbose_name': 'comprobante',
                'verbose_name_plural': 'comprobantes',
                'db_table': 't_comprobantes',
            },
        ),
    ]
