# Generated by Django 5.1.4 on 2024-12-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtemploadmin', '0018_comprobantemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='clienteTipoIdentificacion',
            field=models.CharField(choices=[('ruc', 'RUC'), ('dni', 'DNI')], db_column='cliente_tipo_identificacion', default='dni', max_length=10, verbose_name='DNI/RUC'),
        ),
    ]
